services:
  postgres:
    image: postgres:15.8
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=deduplication
    volumes:
      - stored-data:/var/lib/postgresql/data
      #- ./scripts:/docker-entrypoint-initdb.d/
    ports:
      - "5501:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testuser -d deduplication" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  service:
    image: alexandermey/data-deduplication-service:enviroment_sl
    volumes:
      - .:/usr/application/src
      - build-data:/usr/application/build
volumes:
  stored-data:
  build-data: