name: Build and Test

on:
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.8
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: deduplication
        ports:
          - "5501:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: alexandermey/data-deduplication-service:enviroment_sl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ./src
      - name: Build and set logging directory
        run: |
          mkdir logs
          cp -r src/conf/ conf/
          
          wget -q https://github.com/AlexanderMeynik/data_deduplication_service/releases/download/fixture/testDirectories.zip
          unzip -q testDirectories.zip
          rm testDirectories.zip

          mkdir build && cd build
          
          cmake -G Ninja -DCMAKE_C_COMPILER:PATH="/usr/bin/clang" \
          -DCMAKE_CXX_COMPILER:PATH="/usr/bin/clang++" \
          ../src/
          ninja
      - name: Run benchmark
        if: success() || failure()
        run: |
          cd ${GITHUB_WORKSPACE}/build/test
          GLOG_log_dir=${GITHUB_WORKSPACE}/logs ./benchmark
      - name: Save benchmake results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: bench
          path: /__w/data_deduplication_service/data_deduplication_service/build/test
          if-no-files-found: warn
          include-hidden-files: true
      - name: Save log files
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: /__w/data_deduplication_service/data_deduplication_service/logs
          if-no-files-found: warn
          include-hidden-files: true
