name: Build and Test

on:
  push:
    paths:
      - .github/workflows/ci.yml
      - src/**
      - include/**
      - test/**
      - CMakeLists.txt
env:
    copyPath: /home/app/src
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.8
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: deduplication
        ports:
          - "5501:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: alexandermey/data-deduplication-service:enviroment_sl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ./src
      - name: Build and set logging directory
        run: |
          mkdir -p ${copyPath}
          mkdir -p ${copyPath}/../conf
          mkdir ${GITHUB_WORKSPACE}/logs
          
          cd src
          wget https://github.com/AlexanderMeynik/data_deduplication_service/releases/download/fixture/testDirectories.zip
          unzip -q testDirectories.zip
          rm testDirectories.zip
          cd ..
          
          mkdir build && cd build
          cp -r ../src/conf/ ../conf
          cp -r ../src/conf/ ${copyPath}/../conf
          cmake -G Ninja -DCMAKE_C_COMPILER:PATH="/usr/bin/clang" \
          -DCMAKE_CXX_COMPILER:PATH="/usr/bin/clang++" \
          ../src/
          ninja
          cp -a ${GITHUB_WORKSPACE}/src/. ${copyPath}/
      - name: Save build
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: /__w/data_deduplication_service/data_deduplication_service/build
          if-no-files-found: warn
          include-hidden-files: true
      - name: Run clockArrayTests
        run: |
          cd ${copyPath}/build/test
          ./clock_array_tests
      - name: Run fileServiceTests
        if: success() || failure()
        run: |
          cd ${copyPath}/build/test
          GLOG_log_dir=${GITHUB_WORKSPACE}/logs ./FileServiceTests
      - name: Run benchmark
        if: success() || failure()
        run: |
          cd ${copyPath}/build/test
          GLOG_log_dir=${GITHUB_WORKSPACE}/logs ./benchmark
      - name: Save benchmake results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: bench
          path: /home/app/src/build/test
          if-no-files-found: warn
          include-hidden-files: true
      - name: Save log files
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: /__w/data_deduplication_service/data_deduplication_service/logs
          if-no-files-found: warn
          include-hidden-files: true
