name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.8
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: deduplication
        ports:
          - "5501:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: alexandermey/data-deduplication-service:enviroment_sl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./src

      - name: Build application
        run: |
          ls
          echo "src"
          ls src
          echo "build"
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_C_COMPILER:PATH="/usr/bin/clang" \
          -DCMAKE_CXX_COMPILER:PATH="/usr/bin/clang++" \
          ../src/
          ninja

      - name: run tests
        run: |
          cd test
          cd /__w/data_deduplication_service/data_deduplication_service/build/test && GLOG_logtostderr=0;GLOG_stderrthreshold=0 ./FileServiceTests
