name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: alexandermey/data-deduplication-service:enviroment_sl
    services:
      postgres:
        image: postgres:15.8
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: deduplication
        ports:
          - "5501:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: cd_dir
        run: |
          cd /home/runner/work/data_deduplication_service/data_deduplication_service/

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test service
        run: |
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_C_COMPILER:PATH="/usr/bin/clang" -DCMAKE_CXX_COMPILER:PATH="/usr/bin/clang++" ..
          ninja
          cd test
          ctest --output-on-failure
