name: Build and Test

on:
  push:
    paths:
      - .github/workflows/ci.yml
      - src/**
      - include/**
      - test/**
      - CMakeLists.txt
      - Dockerfile

jobs:
  call_docker_wf:
    uses: ./.github/workflows/docker_build.yml
    secrets:
     DOCKER_PASSWORD=${{secrets.DOCKER_PASSWORD}}
     DOCKER_USERNAME=${{secrets.DOCKER_USERNAME}}
    #if: contains(github.event.head_commit.modified, 'Dockerfile')
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.8
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: deduplication
        ports:
          - "5501:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: alexandermey/data-deduplication-service:enviroment_sl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ./src
      - name: Build and set logginf directory
        run: |
          mkdir ${GITHUB_WORKSPACE}/logs
          mkdir build && cd build
          cp -r ../src/conf/ ../conf 
          cmake -G Ninja -DCMAKE_C_COMPILER:PATH="/usr/bin/clang" \
          -DCMAKE_CXX_COMPILER:PATH="/usr/bin/clang++" \
          ../src/
          ninja
      - name: Run tests
        run: |
          cd ${GITHUB_WORKSPACE}/build/test
          GLOG_log_dir=${GITHUB_WORKSPACE}/logs ./FileServiceTests
          echo ${{github.event.head_commit.modified}}
      - name: Save log files
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: /__w/data_deduplication_service/data_deduplication_service/logs
          if-no-files-found: warn
          include-hidden-files: true
