name: Build and Test

on:
  push:
    paths-ignore:
      - sripts/**
      - README.md
      - documentation/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.8
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: password
          POSTGRES_DB: deduplication
        ports:
          - "5501:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: alexandermey/data-deduplication-service:enviroment_sl
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          path: ./src

      - name: Build and run tests
        run: |
          mkdir ${GITHUB_WORKSPACE}/logs
          chmod -R 777 ${GITHUB_WORKSPACE}/logs
          mkdir build && cd build
          cp -r ../src/conf/ ../conf 
          cmake -G Ninja -DCMAKE_C_COMPILER:PATH="/usr/bin/clang" \
          -DCMAKE_CXX_COMPILER:PATH="/usr/bin/clang++" \
          ../src/
          ninja
          cd test
          GLOG_log_dir=${GITHUB_WORKSPACE}/logs;GLOG_logtostderr=0;GLOG_stderrthreshold=0 ./FileServiceTests
          ls ${GITHUB_WORKSPACE}/logs

      - name: Save log files
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: |
            ${GITHUB_WORKSPACE}/logs